<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." name="DigitalDostoevsky" default="all">
    <description>Build for Digital Dostoevsky</description>
    
    <property name="projectDir" value="${basedir}"/>
    <property name="utilitiesDir" value="${projectDir}/utilities"/>
    <property name="libDir" value="${projectDir}/utilities/lib"/>
    <property name="schemaDir" value="${projectDir}/schema"/>
    <property name="textsDir" value="${projectDir}/texts"/>
    
    <property name="outputDir" value="${projectDir}/_public"/>
    <property name="saxon.jar" value="${libDir}/saxon/saxon-he-12.9.jar"/>
    <property name="schema.basename" value="dostoevschema"/>
    <property name="schema.odd" value="${schemaDir}/${schema.basename}.odd"/>
    <property name="schema.processedodd" value="${schemaDir}/${schema.basename}.processed.odd"/>
    <property name="schema.lite" value="${schemaDir}/${schema.basename}.lite.odd"/>
    <property name="schema.html" value="${outputDir}/${schema.basename}.html"/>
    <property name="schema.rng" value="${schemaDir}/${schema.basename}.rng"/>
                                    
    <fileset id="texts" dir="${textsDir}">
        <include name="**/*.xml"/>
    </fileset>
    
    <!--Clean up old products and make the output dir-->
    <target name="init">
        <description>
            target: init
            
            Deletes any existing products and creates
            the outputDir.
        </description>
        <delete dir="${outputDir}"/>
        <mkdir dir="${outputDir}"/>
    </target>
    
    <!--Validate all of the files-->
    <target name="validate.rng">
        <description>
            target: validate.rng
        
            Validates all files in textsDir
            against an RNG file.
        </description>
        <apply executable="java" parallel="true">
            <arg line="-jar ${libDir}/jing.jar"/>
            <arg value="${schema.rng}"/>
            <fileset refid="texts"/>
        </apply>
    </target>
    
    <target name="validate.sch">
        <java jar="${saxon.jar}" fork="true">
            <arg line="-xsl:${libDir}/xsl-schematron/validate.xsl"/>
            <arg line="-s:${libDir}/xsl-schematron/validate.xsl"/>
            <arg line="rng=${schema.rng}"/>
            <arg line="dir=${textsDir}"/>
        </java>
    </target>
    
    <!-- Runs various diagnostics over the corpus of encoded novels.
        See "diagnostics.xsl" for details -->
    <target name="diagnostics">
        <java jar="${saxon.jar}" fork="true">
            <arg line="-xsl:${utilitiesDir}/diagnostics.xsl"/>
            <arg line="-it:go"/>
            <arg line="outputDir=${outputDir}"/>
        </java>
    </target>
    
    <!-- Extracts speech data from the corpus of encoded novels.
        See "Extraction_code.xsl for details. -->
    <target name="allData">
        <java jar="${saxon.jar}" fork="true">
            <arg line="-xsl:${utilitiesDir}/networks/Extraction_code.xsl"/>
            <arg line="-it:allData"/>
            <arg line="outputDir=${outputDir}"/>
        </java>
    </target>
    
    <target name="odd.processed">
        <java jar="${saxon.jar}" fork="true">
            <arg line="-s:${schema.odd}"/>
            <arg line="-o:${schema.processed.odd}"/>
            <arg line="-xsl:${utilitiesDir}/lib/tei-stylesheets/odds/odd2odd.xsl"/>
        </java> 
    </target>
    
    <target name="odd.lite">
        <java jar="${saxon.jar}" fork="true">
            <arg line="-s:${schema.processed.odd}"/>
            <arg line="-o:${schema.lite}"/>
            <arg line="-xsl:${utilitiesDir}/lib/tei-stylesheets/odds/odd2lite.xsl"/>
        </java> 
    </target>
    
    <target name="odd.html">
        <java jar="${saxon.jar}" fork="true">
            <arg line="-s:${schema.lite}"/>
            <arg line="-o:${schema.html}"/>
            <arg line="-xsl:${utilitiesDir}/lib/tei-stylesheets/html/html.xsl"/>
        </java> 
    </target>
    
    <target name="clean">
        <delete file="${schema.processed.odd}"/>
        <delete file="${schema.lite}"/>
    </target>
    
<!--    <target name="networks">
        <java jar="${saxon.jar}" fork="true">
            <arg line="-xsl:${utilitiesDir}/networks/Extraction_code.xsl"/>
            <arg line="-it:all"/>
            <arg line="outputDir=${outputDir}"/>
        </java>
    </target>
    
    <target name="networkTest">
        <java jar="${saxon.jar}" fork="true">
            <arg line="-xsl:${utilitiesDir}/networks/Extraction_code.xsl"/>
            <arg line="-it:test"/>
            <arg line="outputDir=${outputDir}"/>
        </java>
    </target>

    <target name="masterNetwork">
        <java jar="${saxon.jar}" fork="true">
            <arg line="-xsl:${utilitiesDir}/networks/Extraction_code.xsl"/>
            <arg line="-it:masterNetwork"/>
            <arg line="outputDir=${outputDir}"/>
        </java>
    </target>-->

    <target name="validate" depends="validate.rng, validate.sch"/>
    
    <target name="docs" depends="odd.processed, odd.lite, odd.html">
        <description>Building html documentation</description>   
    </target>
    
    
    <target name="all" depends="init, validate, diagnostics, allData, docs, clean"/>
    
    
    
</project>